
services:
  kafka-0:
    image: bitnamilegacy/kafka:3.4
    ports:
      - "9094:9094"
    environment:
      - KAFKA_ENABLE_KRAFT=yes
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=broker,controller
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka-0:9093,1@kafka-1:9093,2@kafka-2:9093
      - KAFKA_KRAFT_CLUSTER_ID=abcdefghijklmnopqrstuv
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9094
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka-0:9092,EXTERNAL://127.0.0.1:9094
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT
    volumes:
      - kafka_0_data:/bitnami/kafka
    networks:
      - kafka-network
  
  kafka-1:
    image: bitnamilegacy/kafka:3.4
    ports:
      - "9095:9095"
    environment:
      - KAFKA_ENABLE_KRAFT=yes
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_NODE_ID=1
      - KAFKA_CFG_PROCESS_ROLES=broker,controller
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka-0:9093,1@kafka-1:9093,2@kafka-2:9093
      - KAFKA_KRAFT_CLUSTER_ID=abcdefghijklmnopqrstuv
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9095
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka-1:9092,EXTERNAL://127.0.0.1:9095
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT
    volumes:
      - kafka_1_data:/bitnami/kafka
    networks:
      - kafka-network
  
  kafka-2:
    image: bitnamilegacy/kafka:3.4
    ports:
      - "9096:9096"
    environment:
      - KAFKA_ENABLE_KRAFT=yes
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_NODE_ID=2
      - KAFKA_CFG_PROCESS_ROLES=broker,controller
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka-0:9093,1@kafka-1:9093,2@kafka-2:9093
      - KAFKA_KRAFT_CLUSTER_ID=abcdefghijklmnopqrstuv
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9096
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka-2:9092,EXTERNAL://127.0.0.1:9096
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT
    volumes:
      - kafka_2_data:/bitnami/kafka
    networks:
      - kafka-network
  
  schema-registry:
    image: confluentinc/cp-schema-registry:7.9.5
    depends_on:
      - kafka-0
      - kafka-1
      - kafka-2
    ports:
        - "8081:8081"
    environment:
        - SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS=PLAINTEXT://kafka-1:9092,kafka-2:9092,kafka-0:9092
        - SCHEMA_REGISTRY_HOST_NAME=schema-registry
        - SCHEMA_REGISTRY_LISTENERS=http://0.0.0.0:8081
    networks:
        - kafka-network
    volumes:
        - schema-registry-data:/var/lib/schema-registry

  ui:
    image: provectuslabs/kafka-ui:v0.7.0
    ports:
      - "8080:8080"
    environment:
      - KAFKA_CLUSTERS_0_BOOTSTRAP_SERVERS=kafka-0:9092,kafka-1:9092,kafka-2:9092
      - KAFKA_CLUSTERS_0_NAME=kraft
    networks:
      - kafka-network
    depends_on:
     - kafka-0
     - kafka-1
     - kafka-2

  producer:
    build:
      context: .
      dockerfile: Dockerfile
      network: host
    command: ["/bin/sh", "-c", "sleep 10 && /app/yandex-kafka producer"]
    env_file: ./.env
    networks:
      - kafka-network
    depends_on:
     - kafka-0
     - kafka-1
     - kafka-2
     - schema-registry
  
  consumer-1:
    build:
      context: .
      dockerfile: Dockerfile
      network: host
    command: ["/bin/sh", "-c", "sleep 10 && /app/yandex-kafka-consumer consumer"]
    env_file: ./.env
    environment:
      - ENABLE_SINGLE_MESSAGE_CONSUMER=true
      - GROUP_ID=test-group-1
    networks:
      - kafka-network
    depends_on:
     - kafka-0
     - kafka-1
     - kafka-2
     - schema-registry
  
  consumer-2:
    build:
      context: .
      dockerfile: Dockerfile
      network: host
    command: ["/bin/sh", "-c", "sleep 10 && /app/yandex-kafka-consumer consumer"]
    env_file: ./.env
    environment:
      - ENABLE_SINGLE_MESSAGE_CONSUMER=false
      - GROUP_ID=test-group-2
    networks:
      - kafka-network
    depends_on:
     - kafka-0
     - kafka-1
     - kafka-2
     - schema-registry
    deploy:
      replicas: 2

volumes:
  kafka_0_data:
  kafka_1_data:
  kafka_2_data:
  schema-registry-data:

networks:
  kafka-network:
    driver: bridge